{% set name = "filequery" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/filequery-{{ version }}.tar.gz
  sha256: 4e3f0140c56cca55dbcdb9cea780b1addf1d4018211dc303073357607471e484

build:
  entry_points:
    - filequery = filequery:fq_cli_handler
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - python-duckdb ==0.10.1
    - importlib-metadata ==6.8.0
    - linkify-it-py ==2.0.2
    - markdown-it-py ==3.0.0
    - mdit-py-plugins ==0.4.0
    - mdurl >=0.1.2
    # numpy 1.26.1 not available on Conda Forge, loosening pin here
    - numpy >=1.26.1
    - pygments ==2.16.1
    - rich ==13.6.0
    - textual ==0.47.1
    - tree_sitter ==0.20.2
    - tree_sitter_languages ==1.8.0
    - typing-extensions ==4.8.0
    - uc-micro-py ==1.0.2
    - zipp ==3.17.0

test:
  imports:
    - filequery
  commands:
    # Disabling pip check due to lack of numpy 1.26.1 on Conda Forge
    # - pip check
    - filequery --help
  requires:
    - pip

about:
  home: https://github.com/MarkyMan4/filequery
  summary: Query CSV and Parquet files using SQL
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
